=== Superposition28/TheSimpsonsGame-PS3/Godot/Game.Dev/rootfiles/Json/scene_config_schema/scene_entry.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "scene_entry.schema.json",
  "title": "SceneEntry",
  "type": "object",
  "properties": {
    "type": {
      "const": "scene"
    },
    "name": {
      "type": "string"
    },
    "path": {
      "type": "string",
      "description": "Save path for the .tscn (relative to res://)."
    },
    "class": {
      "type": "string",
      "description": "Root class to instantiate (defaults to Node)."
    },
    "script": {
      "type": "string",
      "description": "Script path to attach to the scene root."
    },
    "editable_children_default": {
      "type": "boolean",
      "default": true,
      "description": "Default for marking direct child instances editable in the editor."
    },
    "children": {
      "type": "array",
      "items": {
        "$ref": "child_entry.schema.json"
      }
    }
  },
  "required": [
    "type",
    "name",
    "path"
  ],
  "additionalProperties": false,
  "description": "Top-level scene definition."
}

=== Superposition28/TheSimpsonsGame-PS3/Game.Dev/rootfiles/Json/Node4D/Node3D/Levels/BargainBin.json
[
    {
        "name": "BargainBin",
        "path": "Node4D/Node3D/Levels/BargainBin.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "bargainbin3D",
            "Type": "Node",
            "class": "Node3D",
            "config": {
                "transform": {
                    "position": {"x": -1000, "y": -1100.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            }
        }]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Game/rootfiles/Json/Node4D/Node3D/Levels/DayOfTheDolphin.json
[
    {
        "name": "DayOfTheDolphin",
        "path": "Node4D/Node3D/Levels/DayOfTheDolphin.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "dayofthedolphins3D",
            "Type": "Node",
            "class": "Node3D",
            "config": {
                "transform": {
                    "position": {"x": 1000, "y": -800.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            }
        }]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/Game/rootfiles/Json/Node4D/Node3D/Levels/L10_BargainBin.json
[
    {
        "name": "L10_BargainBin",
        "path": "Node4D/Node3D/Levels/L10_BargainBin.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "bargainbin3D",
            "Type": "Node",
            "class": "Node3D",
            "config": {
                "transform": {
                    "position": {"x": -1000, "y": -1100.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            }
        }]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/Game/rootfiles/Json/Node4D/Node3D/Levels/LHub-00_GameHub.json
[
    {
        "name": "LHub-00_GameHub",
        "path": "Node4D/Node3D/Levels/LHub-00_GameHub.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "GameHub3D",
            "Type": "Node",
            "class": "Node3D",
            "path": "Node4D/Node3D/Levels/LHub-00_GameHub/GameHub3D.tscn",
            "config": {
                "transform": {
                    "position": {
                        "x": -400,
                        "y": 100.111,
                        "z": 0
                    },
                    "rotation_degrees": {
                        "x": 0,
                        "y": 0,
                        "z": 0
                    },
                    "scale": {
                        "x": 1,
                        "y": 1,
                        "z": 1
                    }
                }
            },
            "children": [
                {
                    "name": "Zone01_Terrain",
                    "path": "assets/LHub-00_GameHub/gamehub/zone01_str/assets/environs_zone01/export/terrain/lodmodel1_a70bb3.rws.PS3.glb",
                    "index": {
                        "index_id": 1679,
                        "index_source_file_name": "lodmodel1.rws.PS3.glb",
                        "index_source_path": "gamehub/gamehub/zone01_str/assets/environs/gamehub/gamehub/zone01/export/terrain/lodmodel1.rws.PS3.glb",
                        "index_file_hash": "67678fab59dafe54691bb30789e7d32e282beb505ea7083b62f9aaa2322e43bc",
                        "paths": [
                            "LHub-00_GameHub/gamehub/zone01_str/assets/environs_zone01/export/terrain/lodmodel1_a70bb3.rws.PS3.glb",
                            "gamehub/gamehub/zone01_str/assets/environs/gamehub/gamehub/zone01/export/terrain/lodmodel1.rws.PS3.glb"
                        ]
                    },
                    "collision": {
                        "enabled": true,
                        "shapePlacement": "StaticBodyChild",
                        "ShapeType": "Trimesh",
                        "containerName": "Zone01_Terrain_Mesh_Collisions"
                    }
                }
            ]
        }]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/Game/rootfiles/Json/Node4D/Node3D/Levels/MobRules.json
[
    {
        "name": "MobRules",
        "path": "Node4D/Node3D/Levels/MobRules.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "mob_rules3D",
            "Type": "Node",
            "class": "Node3D",
            "config": {
                "transform": {
                    "position": {"x": 1000, "y": -600.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            }
        }]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/Game/rootfiles/Json/Node4D/Node3D/Levels.json
[
    {
        "name": "Levels",
        "path": "Node4D/Node3D/Levels.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [
            {
                "name": "LHub-00_GameHub",
                "path": "Node4D/Node3D/Levels/LHub-00_GameHub.tscn",
                "config_file": "Node4D/Node3D/Levels/LHub-00_GameHub.json"
            },
            {
                "name": "LHub-00_SprHub",
                "path": "Node4D/Node3D/Levels/LHub-00_SprHub.tscn",
                "config_file": "Node4D/Node3D/Levels/LHub-00_SprHub.json"
            },
            {
                "name": "L01_LandOfChocolate",
                "path": "Node4D/Node3D/Levels/L01_LandOfChocolate.tscn",
                "config_file": "Node4D/Node3D/Levels/L01_LandOfChocolate.json"
            },
            {
                "name": "L02_BartmanBegins",
                "path": "Node4D/Node3D/Levels/L02_BartmanBegins.tscn",
                "config_file": "Node4D/Node3D/Levels/L02_BartmanBegins.json"
            },
            {
                "name": "L03_HungryHungryHomer",
                "path": "Node4D/Node3D/Levels/L03_HungryHungryHomer.tscn",
                "config_file": "Node4D/Node3D/Levels/L03_HungryHungryHomer.json"
            },
            {
                "name": "L04_TreeHugger",
                "path": "Node4D/Node3D/Levels/L04_TreeHugger.tscn",
                "config_file": "Node4D/Node3D/Levels/L04_TreeHugger.json"
            },
            {
                "name": "L05_MobRules",
                "path": "Node4D/Node3D/Levels/L05_MobRules.tscn",
                "config_file": "Node4D/Node3D/Levels/L05_MobRules.json"
            },
            {
                "name": "L06_EnterTheCheatrix",
                "path": "Node4D/Node3D/Levels/L06_EnterTheCheatrix.tscn",
                "config_file": "Node4D/Node3D/Levels/L06_EnterTheCheatrix.json"
            },
            {
                "name": "L07_DayOfTheDolphin",
                "path": "Node4D/Node3D/Levels/L07_DayOfTheDolphin.tscn",
                "config_file": "Node4D/Node3D/Levels/L07_DayOfTheDolphin.json"
            },
            {
                "name": "L08_TheColossalDonut",
                "path": "Node4D/Node3D/Levels/L08_TheColossalDonut.tscn",
                "config_file": "Node4D/Node3D/Levels/L08_TheColossalDonut.json"
            },
            {
                "name": "L09_Invasion",
                "path": "Node4D/Node3D/Levels/L09_Invasion.tscn",
                "config_file": "Node4D/Node3D/Levels/L09_Invasion.json"
            },
            {
                "name": "L10_BargainBin",
                "path": "Node4D/Node3D/Levels/L10_BargainBin.tscn",
                "config_file": "Node4D/Node3D/Levels/L10_BargainBin.json"
            },
            {
                "name": "L11_NeverQuest",
                "path": "Node4D/Node3D/Levels/L11_NeverQuest.tscn",
                "config_file": "Node4D/Node3D/Levels/L11_NeverQuest.json"
            },
            {
                "name": "L12_GrandTheftScratchy",
                "path": "Node4D/Node3D/Levels/L12_GrandTheftScratchy.tscn",
                "config_file": "Node4D/Node3D/Levels/L12_GrandTheftScratchy.json"
            },
            {
                "name": "L13_MedalOfHomer",
                "path": "Node4D/Node3D/Levels/L13_MedalOfHomer.tscn",
                "config_file": "Node4D/Node3D/Levels/L13_MedalOfHomer.json"
            },
            {
                "name": "L14_BigSuperHappy",
                "path": "Node4D/Node3D/Levels/L14_BigSuperHappy.tscn",
                "config_file": "Node4D/Node3D/Levels/L14_BigSuperHappy.json"
            },
            {
                "name": "L15_Rhymes",
                "path": "Node4D/Node3D/Levels/L15_Rhymes.tscn",
                "config_file": "Node4D/Node3D/Levels/L15_Rhymes.json"
            },
            {
                "name": "L16_MeetThyPlayer",
                "path": "Node4D/Node3D/Levels/L16_MeetThyPlayer.tscn",
                "config_file": "Node4D/Node3D/Levels/L16_MeetThyPlayer.json"
            }
        ]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/Game.Dev/rootfiles/Json/Node4D/Node3D/Levels/NeverQuest.json
[
    {
        "name": "NeverQuest",
        "path": "Node4D/Node3D/Levels/NeverQuest.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "neverquest3D",
            "Type": "Node",
            "class": "Node3D",
            "config": {
                "transform": {
                    "position": {"x": 0, "y": -1200.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            }
        }]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/GodotGame/SimpsonsGamePS3_1/Json/Node4D/Node3D/Levels/L13_MedalOfHomer.json
[
    {
        "name": "L13_MedalOfHomer",
        "path": "Node4D/Node3D/Levels/L13_MedalOfHomer.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "medal_of_homer3D",
            "Type": "Node",
            "class": "Node3D",
            "path": "Node4D/Node3D/Levels/L13_MedalOfHomer/medal_of_homer3D.tscn",
            "config": {
                "transform": {
                    "position": {"x": 0, "y": -1400.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            }
        }]
    }
]
