=== Superposition28/TheSimpsonsGame-PS3/Godot/Game.Dev/rootfiles/Json/scene_config_schema/scene_entry.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "scene_entry.schema.json",
  "title": "SceneEntry",
  "type": "object",
  "properties": {
    "type": {
      "const": "scene"
    },
    "name": {
      "type": "string"
    },
    "path": {
      "type": "string",
      "description": "Save path for the .tscn (relative to res://)."
    },
    "class": {
      "type": "string",
      "description": "Root class to instantiate (defaults to Node)."
    },
    "script": {
      "type": "string",
      "description": "Script path to attach to the scene root."
    },
    "editable_children_default": {
      "type": "boolean",
      "default": true,
      "description": "Default for marking direct child instances editable in the editor."
    },
    "children": {
      "type": "array",
      "items": {
        "$ref": "child_entry.schema.json"
      }
    }
  },
  "required": [
    "type",
    "name",
    "path"
  ],
  "additionalProperties": false,
  "description": "Top-level scene definition."
}

=== Superposition28/TheSimpsonsGame-PS3/Godot/Game.Dev/rootfiles/Json/Node4D/Node2D/Terminal_ControlNode.json
[
    {
        "name": "Terminal_ControlNode",
        "path": "Node4D/Node2D/Terminal_ControlNode.tscn",
        "script": "Node4D/Node2D/Terminal_ControlNode.gd",
        "class": "Control",
        "type": "scene",
        "children": [
            {
                "name": "CanvasLayer",
                "class": "CanvasLayer",
                "path": "Node4D/Node2D/Terminal_ControlNode/CanvasLayer.tscn",
                "config_file": "Node4D/Node2D/Terminal_ControlNode/CanvasLayer.json",
                "type": "scene"
            }
        ]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/Game/rootfiles/Json/Node4D/Node3D/Characters/bart.json
[
    {
        "name": "Bart",
        "path": "Node4D/Node3D/Characters/all/bart.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [
            {
                "name": "bart",
                "path": "assets/A2_Characters/GlobalFolder/costumes/costume_bart_default_str/assets_chars/bart/bound_export/lod2_model_1a1244.dff.PS3.glb",
                "config": {
                    "transform": {
                        "position": {"x": -2000, "y": -2000, "z": 0},
                        "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                        "scale": {"x": 1, "y": 1, "z": 1}
                    }
                },
                "collision": {
                    "enabled": true,
                    "shapePlacement": "StaticBodyChild",
                    "ShapeType": "Trimesh",
                    "containerName": "bart_collision"
                }
            },
            {
                "name": "bartman",
                "path": "assets/A2_Characters/GlobalFolder/costumes/costume_bart_default_str/assets_chars/bartman/bound_export/lod1_model_30b841.dff.PS3.glb",
                "config": {
                    "transform": {
                        "position": {"x": -2000, "y": -2000, "z": 10},
                        "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                        "scale": {"x": 1, "y": 1, "z": 1}
                    }
                },
                "collision": {
                    "enabled": true,
                    "shapePlacement": "StaticBodyChild",
                    "ShapeType": "Trimesh",
                    "containerName": "bartman_collision"
                }
            },
            {
                "name": "bart_robo",
                "path": "assets/A2_Characters/GlobalFolder/costumes/costume_bart_default_str/assets_chars/bart_robo/bound_export/lod2_model_00eda9.dff.PS3.glb",
                "config": {
                    "transform": {
                        "position": {"x": -2000, "y": -2000, "z": 20},
                        "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                        "scale": {"x": 1, "y": 1, "z": 1}
                    }
                },
                "collision": {
                    "enabled": true,
                    "shapePlacement": "StaticBodyChild",
                    "ShapeType": "Trimesh",
                    "containerName": "bart_robo_collision"
                }
            }
        ]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Game.Dev/rootfiles/Json/Node4D/Node3D/Levels/TheLandOfChocolate.json
[
    {
        "name": "TheLandOfChocolate",
        "path": "Node4D/Node3D/Levels/TheLandOfChocolate.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "LOC3D",
            "Type": "Node",
            "class": "Node3D",
            "config": {
                "transform": {
                    "position": {"x": 1000, "y": -200.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            },
            "children": [
                {
                    "name": "Zone01_Terrain",
                    "index": {
                        "index_id": 2189,
                        "index_source_file_name": "lodmodel1.rws.PS3.glb",
                        "index_source_path": "loc/loc/zone01_str/build/PS3/pal_en/assets/environs/loc/loc/zone01/export/terrain/lodmodel1.rws.PS3.glb",
                        "index_file_hash": "bfa26bea3bd6317e7a6bc0b7e1f39a3b4239670cc633e5cc5218b07bff9c0384",

                        "id": 1635,
                        "uuid": "daa8b5c220f3778b_4a52853376049cdc",
                        "source_file_name": "pal_en_loc_terrain__Kf72avhpjntlodmodel1.rws.PS3.glb",
                        "source_path": "Map_3-01_LandOfChocolate/zone01/environs/terrain/pal_en_loc_terrain__Kf72avhpjntlodmodel1.rws.PS3.glb",
                        "original_path": "Map_3-01_LandOfChocolate/loc/zone01_str/build/PS3/pal_en/assets/environs/loc/loc/zone01/export/terrain/lodmodel1.rws.PS3.glb",
                        "file_hash": "daa8b5c220f3778bad5cc008f7e6f1b7316f3bd0b375ff4f9f359df15a8933f5",
                        "path_hash": "4a52853376049cdc36a1e28583649fa4"

                    },
                    "collision": {
                        "enabled": true,
                        "shapePlacement": "StaticBodyChild",
                        "ShapeType": "Trimesh",
                        "containerName": "LOC_Zone01_Terrain_Mesh_Collisions"
                    },
					"config": {
						"mesh_overrides": [ {
                            "path": "Mesh_0_0",
                            "visible": false
                        }]
					}
                },
                {
                    "name": "Zone02_Terrain",
                    "index": {
                        "index_id": 2190,
                        "index_source_file_name": "lodmodel1.rws.PS3.glb",
                        "index_source_path": "loc/loc/zone02_str/build/PS3/pal_en/assets/environs/loc/loc/zone02/export/terrain/lodmodel1.rws.PS3.glb",
                        "index_file_hash": "3240ea952a8ea9e06dcfb092293f58cbf64bf873c0ffe9fee5f632f3d9d74f9f"
                    },
                    "collision": {
                        "enabled": true,
                        "shapePlacement": "StaticBodyChild",
                        "ShapeType": "Trimesh",
                        "containerName": "LOC_Zone02_Terrain_Mesh_Collisions"
                    }
                },
                {
                    "name": "Zone02_opt",
                    "index": {
                        "index_id": 2191,
                        "index_source_file_name": "opt_model1.rws.PS3.glb",
                        "index_source_path": "loc/loc/zone02_str/build/PS3/pal_en/assets/environs/loc/loc/zone02/opt/export/zone02/opt_model1.rws.PS3.glb",
                        "index_file_hash": "3ac90cb6d5d9b58fba53f608ee296696f301ea0c70b496efc07c1cef322ccaa8"
                    },
                    "collision": {
                        "enabled": true,
                        "shapePlacement": "StaticBodyChild",
                        "ShapeType": "Trimesh",
                        "containerName": "LOC_Zone02_opt_Mesh_Collisions"
                    }
                },
                {
                    "name": "Zone03_Terrain",
                    "index": {
                        "index_id": 2194,
                        "index_source_file_name": "lodmodel1.rws.PS3.glb",
                        "index_source_path": "loc/loc/zone03_str/build/PS3/pal_en/assets/environs/loc/loc/zone03/export/terrain/lodmodel1.rws.PS3.glb",
                        "index_file_hash": "4580305904c51c57f555391cb85647e5231b36572216bc2c946465bf31b7c895"
                    },
                    "collision": {
                        "enabled": true,
                        "shapePlacement": "StaticBodyChild",
                        "ShapeType": "Trimesh",
                        "containerName": "LOC_Zone03_Terrain_Mesh_Collisions"
                    }
                },
                {
                    "name": "Zone04_opt",
                    "index": {
                        "index_id": 2196,
                        "index_source_file_name": "opt_model1.rws.PS3.glb",
                        "index_source_path": "loc/loc/zone04_str/build/PS3/pal_en/assets/environs/loc/loc/zone04/opt/export/zone04/opt_model1.rws.PS3.glb",
                        "index_file_hash": "53f5d216b6d963ea6cdb28dfa437f2d7d80d0524dba7fe62d8a1f9b00c167b7f"
                    },
                    "collision": {
                        "enabled": true,
                        "shapePlacement": "StaticBodyChild",
                        "ShapeType": "Trimesh",
                        "containerName": "LOC_Zone04_opt_Mesh_Collisions"
                    }
                },
                {
                    "name": "Zone04_Terrain",
                    "index": {
                        "index_id": 2195,
                        "index_source_file_name": "lodmodel1.rws.PS3.glb",
                        "index_source_path": "loc/loc/zone04_str/build/PS3/pal_en/assets/environs/loc/loc/zone04/export/terrain/lodmodel1.rws.PS3.glb",
                        "index_file_hash": "9b6ef9bfd10a8418e5f6ac200478479c7f2671de3386f7ea103678cce016c4e1"
                    },
                    "collision": {
                        "enabled": true,
                        "shapePlacement": "StaticBodyChild",
                        "ShapeType": "Trimesh",
                        "containerName": "LOC_Zone04_Terrain_Mesh_Collisions"
                    }
                },
                {
                    "name": "Zone05_Terrain",
                    "index": {
                        "index_id": 2199,
                        "index_source_file_name": "lodmodel1.rws.PS3.glb",
                        "index_source_path": "loc/loc/zone05_str/build/PS3/pal_en/assets/environs/loc/loc/zone05/export/terrain/lodmodel1.rws.PS3.glb",
                        "index_file_hash": "28ecf446760818d77d472826956afa08e010b479aa9a9ea0c9d52d5ec9707edb"
                    },
                    "collision": {
                        "enabled": true,
                        "shapePlacement": "StaticBodyChild",
                        "ShapeType": "Trimesh",
                        "containerName": "LOC_Zone05_Terrain_Mesh_Collisions"
                    }
                },
                {
                    "name": "Zone06_Terrain",
                    "index": {
                        "index_id": 2200,
                        "index_source_file_name": "lodmodel1.rws.PS3.glb",
                        "index_source_path": "loc/loc/zone06_str/build/PS3/pal_en/assets/environs/loc/loc/zone06/export/terrain/lodmodel1.rws.PS3.glb",
                        "index_file_hash": "fc36dcc7bad31129b4e248bb5bd3497ac95a48e12feeecde1a8eedfa69fc7721"
                    },
                    "collision": {
                        "enabled": true,
                        "shapePlacement": "StaticBodyChild",
                        "ShapeType": "Trimesh",
                        "containerName": "LOC_Zone06_Terrain_Mesh_Collisions"
                    }
                }
            ]
        }]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/Core/Json/Node4D/Node3D/Levels/L16_MeetThyPlayer.json
[
    {
        "name": "L16_MeetThyPlayer",
        "path": "Node4D/Node3D/Levels/L16_MeetThyPlayer.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "meetthyplayer3D",
            "Type": "Node",
            "class": "Node3D",
            "path": "Node4D/Node3D/Levels/L16_MeetThyPlayer/meetthyplayer3D.tscn",
            "config": {
                "transform": {
                    "position": {"x": 0, "y": -1700.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            }
        }]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/Game/rootfiles/Json/Node4D/Node3D/Levels/TheColossalDonut.json
[
    {
        "name": "TheColossalDonut",
        "path": "Node4D/Node3D/Levels/TheColossalDonut.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "colossaldonut3D",
            "Type": "Node",
            "class": "Node3D",
            "config": {
                "transform": {
                    "position": {"x": -1000, "y": -900.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            }
        }]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/Game.Dev/rootfiles/Json/Node4D/Node3D/Levels/MedalOfHomer.json
[
    {
        "name": "MedalOfHomer",
        "path": "Node4D/Node3D/Levels/MedalOfHomer.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "medal_of_homer3D",
            "Type": "Node",
            "class": "Node3D",
            "config": {
                "transform": {
                    "position": {"x": 0, "y": -1400.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            }
        }]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Game.Dev/rootfiles/Json/Node4D/Node2D/Terminal_ControlNode/CanvasLayer/Panel.json
[
    {
        "name": "Panel",
        "class": "Panel",
        "path": "Node4D/Node2D/Terminal_ControlNode/CanvasLayer/Panel.tscn",
        "type": "scene",
        "children": [
            {
                "name": "VideoPlayer",
                "class": "VideoStreamPlayer",
                "type": "Node",
                "config_file": "Node4D/Node2D/Terminal_ControlNode/CanvasLayer/Panel/VideoPlayer.json",
                "config": {
                    "offsets": {
                        "offset_left": 0.0,
                        "offset_top": -1.0,
                        "offset_right": 1150.0,
                        "offset_bottom": 645.0
                    }
                }
            },
            {
                "name": "InputField",
                "class": "LineEdit",
                "type": "Node",
                "config_file": "Node4D/Node2D/Terminal_ControlNode/CanvasLayer/Panel/InputField.json",
                "config": {
                    "offsets": {
                        "offset_left": 6.0,
                        "offset_top": 602.0,
                        "offset_right": 1141.0,
                        "offset_bottom": 633.0
                    }
                }
            },
            {
                "name": "OutputField",
                "class": "RichTextLabel",
                "type": "Node",
                "config_file": "Node4D/Node2D/Terminal_ControlNode/CanvasLayer/Panel/OutputField.json",
                "config": {
                    "offsets": {
                        "offset_left": 0.0,
                        "offset_top": 1.0,
                        "offset_right": 1150.0,
                        "offset_bottom": 590.0
                    }
                }
            }
        ]
    }
]

=== Superposition28/TheSimpsonsGame-PS3/Godot/Game/rootfiles/Json/Node4D/Node3D/Levels/L11_NeverQuest.json
[
    {
        "name": "L11_NeverQuest",
        "path": "Node4D/Node3D/Levels/L11_NeverQuest.tscn",
        "class": "Node3D",
        "type": "scene",
        "children": [{
            "name": "neverquest3D",
            "Type": "Node",
            "class": "Node3D",
            "config": {
                "transform": {
                    "position": {"x": 0, "y": -1200.111, "z": 0},
                    "rotation_degrees": {"x": 0, "y": 0, "z": 0},
                    "scale": {"x": 1, "y": 1, "z": 1}
                }
            }
        }]
    }
]
